# Generated by Django 5.1.1 on 2024-09-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtitle',
            name='created_at',
            field=models.DateTimeField(default='2024-09-15T10:48:03.503068+00:00'),
        ),
    ]
